# This is a basic workflow that is manually triggered

name: "[Dev] Server Restart"

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Restart Server"
        # Default value if no value is explicitly provided
        default: ""
        # Input has to be provided for the workflow to run
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow deploys via ssh to our servers
  restarting:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_REMOTE_HOST_DEV }}
          username: ${{ secrets.SSH_REMOTE_USER_DEV }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pm2 restart dev-${{ secrets.APP_NAME }}
